# Generated by Django 4.2.5 on 2023-09-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('data_expiracao', models.DateTimeField()),
                ('max_usos', models.PositiveIntegerField()),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_desconto', models.CharField(choices=[('PERCENTUAL', 'Percentual'), ('VALOR_FIXO', 'Valor Fixo')], max_length=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('primeira_compra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField()),
                ('data_hora_uso', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupons.cupom')),
            ],
        ),
    ]
