# Generated by Django 4.2.5 on 2023-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0002_cliente_cupom_data_criacao_alter_cupom_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
