# Generated by Django 4.2.5 on 2023-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0003_consumo_valor_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cupom',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
