# Generated by Django 4.2.5 on 2023-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0004_alter_consumo_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='desconto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
