# Generated by Django 4.2.5 on 2023-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0005_consumo_desconto_aplicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cupom',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
