# Generated by Django 4.2.5 on 2023-09-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0006_alter_consumo_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cupom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupons.cupom'),
        ),
    ]
