# Generated by Django 4.2.5 on 2023-09-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0007_alter_consumo_cupom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumo',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
